In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
import chart_studio.plotly as py
import plotly.graph_objects as go
from plotly.graph_objs import *
from plotly.offline import iplot

# Load data

In [77]:
df = pd.read_csv("historical_stock_prices.csv")
df_stock_industry = pd.read_csv("historical_stocks.csv")

In [78]:
#df = df_stocks[['ticker','close','date']][0:1000000].copy()

In [79]:
df.head()

  ticker   open  close  adj_close    low   high   volume        date
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900  2013-05-08
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800  2013-05-09
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100  2013-05-10
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400  2013-05-13
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100  2013-05-14

In [80]:
df_stock_industry.head()

,ticker,exchange,name,sector,industry
0,PIH,NASDAQ,"1347 PROPERTY INSURANCE HOLDINGS, INC.",FINANCE,PROPERTY-CASUALTY INSURERS
1,PIHPP,NASDAQ,"1347 PROPERTY INSURANCE HOLDINGS, INC.",FINANCE,PROPERTY-CASUALTY INSURERS
2,TURN,NASDAQ,180 DEGREE CAPITAL CORP.,FINANCE,FINANCE/INVESTORS SERVICES
3,FLWS,NASDAQ,"1-800 FLOWERS.COM, INC.",CONSUMER SERVICES,OTHER SPECIALTY STORES
4,FCCY,NASDAQ,1ST CONSTITUTION BANCORP (NJ),FINANCE,SAVINGS INSTITUTIONS

# Add tech stocks to dataframe

In [81]:
print(df_stock_industry.sector.unique())
techTickers = df_stock_industry[df_stock_industry['sector'] == 'TECHNOLOGY']['ticker']

#for fast lookup of tech stocks
tech_map = map(techTickers.values, np.zeros(len(techTickers)))

print()
print("lenth of tech ticker: {0}".format(len(techTickers)))

['FINANCE' 'CONSUMER SERVICES' 'TECHNOLOGY' 'PUBLIC UTILITIES'
 'CAPITAL GOODS' 'BASIC INDUSTRIES' 'HEALTH CARE' 'CONSUMER DURABLES' nan
 'ENERGY' 'MISCELLANEOUS' 'SECTOR' 'TRANSPORTATION'
 'CONSUMER NON-DURABLES']

lenth of tech ticker: 607

In [88]:
df[df['ticker'] == 'VNET'].reset_index(drop=True)

,ticker,open,close,adj_close,low,high,volume,date
0,VNET,20.260000,18.799999,18.799999,18.34,22.330000,18178500,2011-04-21
1,VNET,19.400000,17.750000,17.750000,17.32,19.500000,2323400,2011-04-25
2,VNET,17.700001,17.559999,17.559999,17.40,18.709999,1800000,2011-04-26
3,VNET,17.840000,16.250000,16.250000,15.80,17.840000,1976500,2011-04-27
4,VNET,16.110001,16.030001,16.030001,15.70,16.780001,1900000,2011-04-28
...,...,...,...,...,...,...,...,...
1844,VNET,9.090000,9.240000,9.240000,8.95,9.730000,653500,2018-08-20
1845,VNET,9.300000,10.510000,10.510000,9.30,10.620000,808700,2018-08-21
1846,VNET,10.450000,10.490000,10.490000,10.37,10.560000,533500,2018-08-22
1847,VNET,10.520000,10.430000,10.430000,10.21,10.560000,369600,2018-08-23
1848,VNET,10.500000,10.950000,10.950000,10.49,10.960000,393300,2018-08-24

In [91]:
df_tech_stocks = pd.DataFrame()
for t in techTickers:
    df_tech_stocks = df_tech_stocks.append(df[df['ticker'] == t])
    print(t)

VNET
TWOU
JOBS
ACIA
ACIW
ACMR
ATVI
ACXM
IOTS
ADBE
AMD
AGYS
AGMH
AIRG
AMCN
ALRM
ALLT
MDRX
AOSL
GOOG
GOOGL
AABA
ALTR
AMBA
DOX
AMRH
AMRHW
AMSWA
AMKR
ASYS
ADI
ANSS
APPF
APPN
AAPL
AMAT
AAOI
APTI
ARRS
ASML
AZPN
ALOT
ASUR
TEAM
ATOM
ATTU
ADSK
ADP
AUTO
AVNW
AVID
AWRE
ACLS
AXTI
BOSC
BIDU
BAND
BBSI
BNFT
BILI
BKYI
BBOX
BLKB
BL
BRQS
EPAY
BLIN
BCOV
AVGO
BVSN
BRKS
CA
CCMP
CDNS
CAMP
CSIQ
CBLK
CARB
CDLX
CARG
CASA
CAVM
CRNT
CERN
CEVA
CYOU
CHKP
CNIT
CCIH
CNET
IMOS
CRUS
CSCO
CTXS
CTSH
CHUBA
CHUBK
COMM
CVLT
CPSI
CTG
CMTL
CVON
CVONW
CSOD
CPAH
COUP
CRAY
CREE
CRTO
CCRN
CSGS
CSPI
CVV
CYBR
CY
CYRN
DWCH
DTRM
DGII
DMRC
DGLY
DIOD
DLHC
DOCU
DBX
DSPG
EBIX
ELON
SATS
EDGW
EGAN
EA
EFII
ELTK
EMKR
EIGI
WATT
ERII
ENPH
PLUS
ERIC
EVBG
MRAM
EVOL
EXTR
FFIV
FB
FNSR
FEYE
FSLR
FISV
FIVN
FLEX
FPAY
FSCT
FRSX
FORM
FORTY
FTNT
FSNN
GDS
GFN
GFNCP
GFNSL
GIGM
GILT
GLUU
GEC
GSUM
GRPN
GVP
GSIT
HQCL
HLIT
HSTM
HSII
HIMX
HDP
HSON
ICHR
ICLK
INVE
INFO
IMMR
IMPV
INOD
ISSC
INOV
INPX
INSE
IDTI
INTC
LINK
IMI
INAP
IIJI
INTX
IVAC
INTU
IPAS
IPGP
JCOM
JASO
JKHY
JMU
KELYA
KELYB
KTCC
KFRC
KE
KONE
KOPN
KLIC
KVHI
LRCX
LTRX
LSCC
LTRPA
LTRPB
LPTH
LECO
LPSN
LOGI
LOGM
LFIN
LORL
MTSI
MGIC
MNGA
MAMS
MANH
MNTX
MRVL
MTCH
MTLS
MATR
MXIM
MGRC
MDCA
MTBC
MTBCP
MDSO
MLNX
MCHP
MU
MSCC
MSFT
MSTR
MIME
MNDO
MB
MIND
MINDP
MITK
MITL
MOBL
MOMO
MDB
MPWR
TYPE
MOSY
MOXC
MYSZ
NNDM
NH
NATI
NETE
NTAP
NLST
NTCT
NTWK
NICE
LASR
NUAN
NTNX
NVEC
NVDA
NXPI
OIIM
OCLR
OKTA
OMCL
ON
OTIV
OSS
OTEX
OSIS
PFIN
PCYG
PRKR
PCTY
PCTI
PDFS
PEGA
PRFT
PERI
PLAB
PXLW
PLXS
PNTR
POWI
LEDS
PSDO
IPDN
PRGS
PFPT
PTC
QADA
QADB
QRVO
QCOM
QSII
QBAK
QLYS
QTNA
QRHC
QUIK
QUMU
SMTC
RDCM
RSYS
RMBS
RPD
RCMT
RNWK
RP
RDVT
RCII
RESN
RBBN
RBCN
RMBL
SABR
SANM
SPNS
SCSC
SGMS
SEAC
STX
SCWX
SGOC
SEII
SHSP
PIXY
SSTI
SWIR
SIFY
SIGM
SGMA
SILC
SLAB
SIMO
SLP
SINA
SWKS
SGH
SMSI
SMTX
SRAX
SCKT
SOHU
SEDG
SOFO
ANY
SPI
SPLK
SPSC
SSNC
STAF
STLR
STLRU
STLRW
SSYS
STRM
SPWR
SMCI
SPCB
SCON
SPRT
SYKE
SYMC
SYNC
SYNA
SNCR
SNPS
SYNT
TTWO
TLND
TECD
TCCO
TXN
DSGX
KEYW
MIDD
TSG
TTD
ULTI
TNTR
TISA
TSEM
TACT
TZOO
TRIP
TRVG
TRUE
TSRI
TTEC
TTMI
TCX
TWIN
UBNT
UCTT
UPLD
VRNS
VDSI
VECO
VRNT
VRSN
VRSK
VERI
VSAT
VIAV
VRTU
VUZI
WSTG
WEB
WB
WDC
WIX
WDAY
WSCI
XLNX
XPER
XPLR
XNET
YNDX
YY
ZBRA
ZIXI
ZS
ZNGA
DDD
WUBA
ATEN
AAN
ATU
AER
HIVE
AL
AYR
AYX
AMBR
AMN
AQ
ANET
ASX
ASGN
AUO
ATHM
BHE
BITA
BKI
BB
BOX
CACI
CAI
CARS
CSLT
CLS
CDAY
ECOM
CMCM
CISN
CLDR
CVG
CLGX
CTS
CW
DQ
DVMT
DOV
DXC
ETN
ELLI
EPAM
EVTC
AQUA
EXTN
FDS
SFUN
FIT
GDI
GTES
GLOB
GDDY
GHM
GWRE
HHS
HPE
HPQ
HMI
HUBS
ITW
INFY
IPHI
NSP
INST
IBM
IPG
INXN
JBL
JT
JKS
JBT
JNPR
KAI
KFY
KYO
LLL
LFGR
LDOS
LN
LKM
LXFT
MX
MAN
MRIN
MAXR
MXL
MFGP
MCRN
MIXT
MODN
MSI
NPTN
NEWR
NOK
NVT
OMC
OOMA
ORCL
PAGS
PANW
PKE
PAYC
PNR
PVTL
PRO
PSTG
QTWO
QTM
RHT
SOL
RENN
RXN
RNG
RHI
RST
SAIL
CRM
SAP
SAIC
SMI
SEND
SQNS
NOW
SHOP
SSTK
SMAR
SNAP
SOGO
SPA
SPXC
FLOW
SQ
SXI
SRT
STM
SWCH
SNX
DATA
TSM
TLRA
TNC
TDC
TGH
RUBI
TRTN
TBI
TWLO
TWTR
TYL
UIS
UMC
URI
VEEV
VMW
WBT
WIT
WK
WPP
XRX
YEXT
YGE
ZEN
ZUO

In [92]:
df_tech_stocks

,ticker,open,close,adj_close,low,high,volume,date
3114938,VNET,20.260000,18.799999,18.799999,18.340000,22.330000,18178500,2011-04-21
3114942,VNET,19.400000,17.750000,17.750000,17.320000,19.500000,2323400,2011-04-25
3114943,VNET,17.700001,17.559999,17.559999,17.400000,18.709999,1800000,2011-04-26
3114944,VNET,17.840000,16.250000,16.250000,15.800000,17.840000,1976500,2011-04-27
3114962,VNET,16.110001,16.030001,16.030001,15.700000,16.780001,1900000,2011-04-28
...,...,...,...,...,...,...,...,...
2961572,ZUO,29.900000,28.299999,28.299999,28.055000,29.990000,971000,2018-08-20
2961582,ZUO,28.280001,28.799999,28.799999,28.231001,29.330000,979800,2018-08-21
2961594,ZUO,28.389999,29.719999,29.719999,28.337000,30.000000,761900,2018-08-22
2961603,ZUO,29.870001,30.170000,30.170000,29.170000,30.850000,1047100,2018-08-23
2961615,ZUO,30.379999,33.380001,33.380001,30.322001,33.480000,1808800,2018-08-24

In [82]:
listOfTechStocks = []

for t in df['ticker'].unique():
    if t in techTickers:
        listOfTechStocks.add(t)
    else:
        indexNames = df[df['ticker'] == t ].index
        df.drop(indexNames , inplace=True)

KeyboardInterrupt:

In [ ]:
df

In [93]:
df_tech_stocks.to_csv('Tech_stock_prices.csv')